# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlphaHealthDoctor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlphaHealthDoctor
pod 'SwiftWebSocket'
pod 'Alamofire', '~> 4.4'
pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'AlphaHealthDoctorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlphaHealthDoctorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
